### ISSUE TITLE
Segmentation Fault on String Literal Assignment in Optional Struct

### ISSUE THREAD

**Issue by tclesius** [c3lang/c3c#1360] opened 2024-08-15 17:13 UTC
`main.c3`
```
import std::io;

struct MyStruct
{
    String x;
}


fn void main()
{
    MyStruct! s;
    s.x = "c3c";
}
```
When compiled with  `c3c compile main.c3` the output yields `Segmentation fault`.

**Comment by lerno** [comment] 2024-08-15 19:19
This should be fixed now. It should have been caught by the semantic checker, just like something like `a[0] = 1` when `a` is an optional. The reason the compiler doesn't permit this is the unclear semantics, what happens if `s` is an optional empty? Does it initialize `s` as if it was written `s = { .x = "c3c" }`, whereas it retains `s.x = "c3c"` if it has a value? Or maybe the right hand side isn't evaluated at all in `s.x = "c3c";`? Both are possible intents. I found none of the uses particularly appealing to support.

**Comment by tclesius** [comment] 2024-08-15 19:45
Yes, thanks for the quick fix. It makes sense not to support ambiguous behavior like this.

**Comment by lerno** [comment] 2024-08-15 20:59
Does it work for you now?

**Comment by tclesius** [comment] 2024-08-16 08:54
Tested it, the error message and line number are correct. Closing the issue.

**Comment by tclesius** [comment] 2024-08-16 14:00
I need to reopen this because i found another bug:
```
struct MyStruct
{
    String s;
}

fn void main()
{
    MyStruct! s;
    l = {};
}
```
also outputs `Segmentation fault` on compilation.

**Comment by tclesius** [comment] 2024-08-16 14:03
```
fn void main()
{
    s = {};
}
```
Maybe related - this also outputs `Segmentation fault`.

**Comment by lerno** [comment] 2024-08-16 14:13
Hmm.. I am not able to reproduce this. Did you have some additional code that helped trigger this?

**Comment by tclesius** [comment] 2024-08-16 14:28
Yes, this seems to be the culprit:
```
import std::collections::map;

fn void main()
{
    HashMap(<String, String>) map;
    map["c3c"] = {};
}
```

**Comment by lerno** [comment] 2024-08-16 14:51
Thank you, it should be fixed now, please try again.

**Comment by tclesius** [comment] 2024-08-16 15:30
Just checked - the previous is working, thanks. However i found the following will also output a segfault:
```
import std::collections::map;

fn void main()
{
    HashMap(<String, HashMap(<String, String>)>) map;
    map["c3c"] = {};
}
```

**Comment by lerno** [comment] 2024-08-16 16:35
I fixed this and another bug, but there might be more to find. I'm grabbing more test cases at the moment and then I'm going to rewrite the root cause of these special cases.

**Comment by lerno** [comment] 2024-08-16 21:08
I think I found the offending code – at least all test cases are passing and the special workarounds have been removed. Report anything else, even if you happen upon something that gives an error and you think that maybe the compiler should accept it.

**Comment by tclesius** [comment] 2024-08-17 09:19
Will do, thanks!

**Closed** 2024-08-19 20:52 UTC
Labels: Bug, Resolved bug
