### ISSUE TITLE
Tests don't run "Could not emit ir to file: No such file or directory"

### ISSUE THREAD

**Issue by MCRusher** [c3lang/c3c#894] opened 2023-07-27 21:46 UTC
Taking an example from the documentation:

```nim
module testingc3;

fn int main() {
    return hello_world();
}

module testingc3 @private;
import std::io;
fn int hello_world() {
    io::printn("Hello, world\n");
    return 0;
}

module testingc3 @test;
fn void test_hello() {
    assert(hello_world() == 0);
    assert(false); // doesn't trigger since tests don't run
}
```

And putting this into a project created with `c3c init ...`

`c3c build` works just fine and the output is as expected.

`c3c test` results in `Could not emit ir to file: No such file or directory`

The test functions get checked for correctness, but the tests don't run.

Removing the addition module declarations and adding `@test` directly to the test function doesn't change anything.

My version info is:

```
C3 Compiler Version (pre-alpha):   0.4.581
Installed directory:               /home/USER/Apps/c3/
LLVM version:                      16.0.6
LLVM default target:               x86_64-pc-linux-gnu
```

And my OS is Linux Mint 21.2 Cinnamon (based on Ubuntu 22.04)

---

As an aside, I've followed this language for a while but recently decided to actually try it out. I like it, it's like a less authoritarian spin on Zig.

**Comment by lerno** [comment] 2023-07-28 08:09
Ok, looks like a regression. I'll look at it asap.

**Comment by lerno** [comment] 2023-07-28 09:17
This should be fixed in `0.4.585`

**Comment by pierrec** [comment] 2023-07-28 12:26
Works now. Thanks!

**Comment by lerno** [comment] 2023-07-28 12:27
Thank you for verifying, closing it.

**Closed** 2023-07-28 12:27 UTC
Labels: bug, fixed needs check
