### ISSUE TITLE
Discussion: Integer Names

### ISSUE THREAD

**Issue by wrenger** [c3lang/c3c#1178] opened 2024-04-07 21:40 UTC
Hi,

First of all, thanks for this cool language. 
I really do like many of its design decisions. Only one seems odd to me and that are C3's integer names. I think C's integer naming is already difficult (due to its history) and unfortunately C3 is not that much better. 

Fortunately you decided for fixed sizes independent from the target architecture but char/short/int/long are only familiar to C devs, which might become confused if these have different sizes than their C counterparts. Names like u8/u16/u32/u64/u128 (and i8/...) are much more meaningful and accurate, and give you the option to support C's char/short/int/long for FFI (although CInt is also fine). And int128 fits a lot better in this naming scheme.

Lastly the isz/usz and iptr/uptr: Again isize/usize is easier and can be said out loud, which is a plus.
Also they are a bit confusing. Are there architectures nowadays where isz and iptr differ? Maybe one architecture dependent integer type (or two with unsigned) is enough?

**Comment by lerno** [comment] 2024-04-07 23:22
Fixing the sizes while using C naming is not uncommon: see C#/Java for example. The downside of i8 etc is one of readability, and also would mean that code would look significantly different from the same C sample. 

```c
// Compare:
for (i8 i = 8; i >= 0; i--) { ... }
// and
for (int i = 8; i >= 0; i--) { ... }
```

Originally I used `i128` for the `int128` type, but I felt that I had to change it to `int128` to increase readability. And if we replace `int` with `int32`, `long` with `int64`, I don't feel much is won.

Regarding `isize` and `usize`:

Originally C3 has `isize`/`usize` and `iptrdiff`/`uptrdiff`. There were one type too many, as they for almost every use would be exactly the same size. However, dropping `iptrdiff` felt unfortunate. This: `&a - &b` seems hardly to be an "isize". The name "isize" is too explicitly a size, and felt incorrect to use. On the other hand, just having `usize`/`iptrdiff` seemed equally odd: not only would it violate the convention, but sometimes something like a signed `usize` is useful, and then `iptrdiff` seemed a bad thing to use.

For that reason the contraction `usz` and `isz` was chosen. They are shorter, but also more abstract, which means "isz" feels more natural to encompass both "isize" and "iptrdiff" usages, without nudging too much towards the "isize" meaning.

As for iptr sizes: Rust has been struggling with it's decision to say usize = uintptr (see https://internals.rust-lang.org/t/pre-rfc-usize-is-not-size-t/15369/28 etc) which seems to hint that conflating them is not a great idea.

**Comment by wrenger** [comment] 2024-04-08 09:26
Hi @lerno, thanks for your detailed answer. 

> Originally I used i128 for the int128 type, but I felt that I had to change it to int128 to increase readability. And if we replace int with int32, long with int64, I don't feel much is won.

Maybe I'm too much accustomed to Rusts integers, as I find them quite readable. However, there (and also in C), I use mostly the usize/size_t types. Only if specific sizes are necessary do I switch to u32/u8 (or uint32_t/uint8_t). I try to avoid using char/short/long directly. I do like that in Rust (and the C stdlib), the integer sizes are encoded in their names. So I would gravitate more to int8/int16, etc, instead of char/short...

Also, char always seemed a bit off to me.
```c
for (char i = 8; i >= 0; i--) { ... } # well no this is an integer not a character here
```

> For that reason the contraction usz and isz was chosen. They are shorter, but also more abstract, which means "isz" feels more natural to encompass both "isize" and "iptrdiff" usages, without nudging too much towards the "isize" meaning.

Understandable, but the downside of these abstract names is that they are harder to understand, remember, and read.

**Comment by wrenger** [comment] 2024-04-08 10:36
Ah thanks I was looking for an issue like this.

**Comment by lerno** [comment] 2024-04-09 07:38
Other C projects have aliases such as Long, Int, UInt etc with known sizes. Originally C3 did use ixx and uxx names and for some time I intended to retain both int and ixx style names.

However, I realized that would be a bad idea, because then this would just end up being another thing for style guides to have to address, as mixing "int" and "ixx" style names would be universally bad. In addition, the standard library would need to standardize on something. Whatever that standard would be would end up being the "canonical" style anyway.

The reason for bit specific aliases in C code is that C does not specify the sizes and that it a big problem. The problem is not the NAMES themselves. It's not that the Linux kernel introduces s32 because "int" was too long or hard to read.

And so there are two possibilities: size-fixing established names or introducing bit-specifying types. And I know the latter is popular *right now*. Bit-specifying types are clear in terms of sizes, but size-fixed conventional names like in Java/C# are proven to work well too. Conventional names have somewhat better readability, and matches C look-and-feel better.

For this reason I went with conventional names. If desired, introduce your own aliases using:
```c
def USize = usz;
def ISize = isz;
def Int8 = ichar;
def UInt8 = char;
def Int16 = short;
def UInt16 = ushort;
// ... etc
```

**Comment by lerno** [comment] 2024-04-09 08:38
> Maybe I'm too much accustomed to Rusts integers, as I find them quite readable. However, there (and also in C), I use mostly the usize/size_t types. Only if specific sizes are necessary do I switch to u32/u8 (or uint32_t/uint8_t). I try to avoid using char/short/long directly. I do like that in Rust (and the C stdlib), the integer sizes are encoded in their names. So I would gravitate more to int8/int16, etc, instead of char/short...

I would say this is a matter of what you're used to.

> ```c
> for (char i = 8; i >= 0; i--) { ... } // well no this is an integer not a character here
> ```

Thanks for reminding me that this is also something I need to always detect as an error. 😬 

>  > For that reason the contraction usz and isz was chosen. They are shorter, but also more abstract, which means "isz" feels more natural to encompass both "isize" and "iptrdiff" usages, without nudging too much towards the "isize" meaning.
> 
> Understandable, but the downside of these abstract names is that they are harder to read, understand, and remember.

Yes, there is always a trade-off (please also consider the fact that "i16" is actually an abstract name as well)

**Comment by lerno** [comment] 2024-04-13 10:50
If there isn't anything else to discuss I'll close this?

**Comment by wrenger** [comment] 2024-04-14 12:58
@lerno, I don't think so. Thanks for clarifying this and explaining your decisions.
Ultimately this is a quite subjective question with no perfect solution.

**Comment by lerno** [comment] 2024-04-15 08:45
@wrenger yes, and not only is it subjective, but what is optimal also depends to some degree on the project itself.

Whether `int` is the better trade-off or `i32` can obviously be debated. I have no really strong preference for either, but the readability issues I experienced with `i32` made me switch to `int`. Note however that if a language would support non-power-of-two integer types, like "i48" then in such a case the `int` scheme would be a non-starter.

Similarly, there were plans to support a many integer types beyond int128 (e.g. int256, int512, int1024 etc) then in that case that would be a strong argument for considering including the bit size in the name.

Incidentally, D uses `cent` for the int128 type, but I found that name rather obscure, which is why I went for the (inconsistent) `int128` name instead. (there are other alternatives, such as `huge` or `octa`, also similarly obscure). There are pros and cons about everything.

**Closed by lerno** 2024-04-15 08:45 UTC
