### ISSUE TITLE
Parametrize `vendor-fetch` download output directory

### ISSUE THREAD

**Issue by MathiasFHemmer** [c3lang/c3c#1460] opened 2024-09-18 13:43 UTC
Make `vendor-fetch` smarter by identifying in the current directory the `project.json` file and look for the lib path and download the files directly into it.

Since the key `dependency-search-paths` is an array, it could use the first entry, or maybe a new key specific for the curated libs? Maybe like `default-lib-path` or something.

It would also be ideal to have it as a parameter of the cli command

**Comment by tomaskallup** [comment] 2024-09-18 13:57
Duplicate of #1422

For people look for a workaround, there is `--path` cli option:
`c3c vendor-fetch raylib5 --path lib`

**Closed** 2024-09-18 14:04 UTC
