### ISSUE TITLE
Assert statements don't properly mark their message arguments as used causing the linker to fail.

### ISSUE THREAD

**Issue by MinekPo1** [c3lang/c3c#1354] opened 2024-08-12 18:27 UTC
Minimal example:

```c
import std::io;

fn String foo() {
    return "hello from foo!";
}

// c3c complains about using assert(false), so we need to trick it
fn bool bar() {
    return false;
}

fn void main() {
    io::printn("Hello, World!");
    assert(bar(), "%s", foo());
}
```

The linker error message is `undefined reference to `<module>.foo'`, we can further confirm this is the case by looking at the object file, where we find `foo` referenced but undefined:

```
000000000 V $ct.char
0000000000000000 V $ct.sa$char
0000000000000000 V $ct.String
0000000000000003 r .file
000000000000000b r .func
0000000000000000 r .L.str
0000000000000000 T <module>_fn.bar
                 U <module>_fn.foo
0000000000000010 T <module>_fn.main
00000000000001a0 T main
0000000000000000 r .panic_msg
                 U std.core.builtin.panicf
                 U std.io.File.flush
                 U std.io.File.write
                 U std.io.File.write_byte
                 U std.io.stdout

```

Tested with c3c 0.6.2, with llvm 17.0.6 targeting `x86_64-pc-linux-gnu` (TODO: test with a master build)

Not sure if its the correct pass, but in [`sema_liveness.c`](https://github.com/c3lang/c3c/blob/9aab962ebca5b9ebdfc9d34a95c5ebcf08a7dd4b/src/compiler/sema_liveness.c#L143-L151) I have found one example of a semantic pass not descending into the message arguments, and "liveness" sounds like it looks for dead code, which feels right.

**Comment by lerno** [comment] 2024-08-12 21:04
This was indeed sema_liveness. It should now be patched. Please close this when you have verified that it works as intended.

**Closed** 2024-08-14 05:38 UTC
Labels: bug, fixed needs check
