### ISSUE TITLE
fetch-vendor gives html if the lib doesnt exist

### ISSUE THREAD

**Issue by anthony-63** [c3lang/c3c#1386] opened 2024-08-26 13:12 UTC
For example ``c3c fetch-vendor test`` will give me a file named ``test.c3l`` and inside of it is just html for github.

**Comment by lerno** [comment] 2024-08-30 13:16
I can't reproduce this on MacOS, what platform is this happening on?

**Comment by lerno** [comment] 2024-08-30 13:32
I am pretty sure this is a windows bug. It doesn't use curl, maybe some friendly soul could have a look at http.c so that it errors when the file is missing.

**Comment by lerno** [comment] 2024-09-01 19:45
This should have been resolved with #1397, can you please check?

**Comment by Hema2-official** [comment] 2024-09-07 13:34
Seems to work fine on Windows 11 Pro 24H2.

**Comment by lerno** [comment] 2024-09-07 13:35
Thank you! I'll close this then.

**Closed by lerno** 2024-09-07 13:35 UTC
Labels: Bug, Help Wanted!, Resolved bug, Toolchain
