### ISSUE TITLE
Continuing in unbounded loop may just exit?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#522] opened 2022-08-10 14:10 UTC
Here's some code I wrote and am doing a bit of printf debugging. The algorithm (in theory) should work whether the input is a char[][] filled with some regex expressions...or* one long concatenated regex expression.

At least in theory the output should be similar, however in the later case I was finding the output was WILDLY different. In fact, it clearly had only done one part of the regex...then exited. This of course was fine in the first case, because each regex was supposed to be only one step's worth.

```c
struct Classification_table {
    char[256] table;
    char[256] collisions;
    uint input_classes;
    uint output_classes;
}

fn Classification_table create_distinct_classfication_table(char[][] regex_char_classes) {
    Classification_table classification_table;

    classification_table.input_classes = regex_char_classes.len;

    char[256] marked;
    usize[256] indexs;

    for (usize i = 0; i < 256; i++) {
        classification_table.table[i] = 0xff;
        marked[i] = (char)false;
    }

    uint target_class = 0;
    //we start collisions here
    uint collision_class = regex_char_classes.len;
    //TODO: handle ()'s as subexpressions
    for (usize r = 0; r < regex_char_classes.len; r++) {
        char[] regex_char_class = regex_char_classes[r];
        bool is_in_char_class = false;
        bool is_char_range = false;
        bool is_alternation = false;
        uint capture_group_depth = 0;

        char first_value = 0;
        char second_value = 0;
        char value = 0;
        bool first_pass = false;

        target_class = (uint)r;

        usize i = 0;
        do {
            is_in_char_class = false;
            is_char_range = false;
            printf("processing: %.*s\n", (regex_char_class.len-i), regex_char_class.ptr+i);
            for REGEX_STEP: (; i < regex_char_class.len; i++) {
                value = 0;
                char c = regex_char_class[i];
                switch(c) {
                case '+':
                    if (is_in_char_class) {
                        value = c;
                        break;
                    }
                    continue;
                case '*':
                    if (is_in_char_class) {
                        value = c;
                        break;
                    }
                    continue;
                case '{':
                    if (is_in_char_class) {
                        value = c;
                        break;
                    }
                    //todo skip {,} or {num,} or {,num} or {num,num}
                case '}':
                    value = c;
                    break;
                case '[':
                    is_in_char_class = true;
                    continue;
                case ']':
                    if (is_in_char_class) {
                        is_in_char_class = false;
                        //exiting char class -> move to next character
                        continue;
                    }
                    value = c;
                case '(':
                    if (!is_in_char_class) {
                        capture_group_depth+=1;
                        continue;
                    }
                    value = '(';
                case ')':
                    if (!is_in_char_class) {
                        if (capture_group_depth > 0) {
                            capture_group_depth-=1;
                            continue;
                        }
                    }
                    //this is a dangling )...probably not a valid regex?
                    value = ')';
                case '|':
                    if (is_in_char_class) {
                        value = '|';
                        break;
                    }
                    is_alternation = true;
                case '\\':
                    //i++;
                    char escaping = regex_char_class[i+1];
                    char base = 2;
                    //uint max_val = ; //0xffffffff

                    switch(escaping) {
                    case '0': nextcase;
                    case '1': nextcase;
                    case '2': nextcase;
                    case '3': nextcase;
                    case '4': nextcase;
                    case '5': nextcase;
                    case '6': nextcase;
                    case '7':
                        base = 8; //octal
                        for (uint x = 0; x < 3; x++) {
                            char v = dfa::CHAR_TO_DIGIT[regex_char_class[i+1]];
                            if (v >= base) {
                                break;
                            }
                            uint nvalue = ((uint)value << 3) + v;
                            if (nvalue > 0xff) {
                                break;
                            }
                            value = (char)nvalue;
                            i++;
                        }
                        break;
                    case 'x': nextcase;
                    case 'X':
                        base = 16;
                        i++;
                        for (uint x = 0; x < 2; x++) {
                            char v = dfa::CHAR_TO_DIGIT[regex_char_class[i+1]];
                            if (v >= base) {
                                break;
                            }
                            uint nvalue = ((uint)value << 4) + v;
                            if (nvalue > 0xff) {
                                break;
                            }
                            value = (char)nvalue;
                            i++;
                        }
                        break;
                    case 'a':
                        value = '\a';
                        i++;
                    case 'b':
                        value = '\b';
                        i++;
                    case 'e':
                        value = '\e';
                        i++;
                    case 'n':
                        value = '\n';
                        i++;
                    case 'r':
                        value = '\r';
                        i++;
                    case 't':
                        value = '\t';
                        i++;
                    case 'v':
                        value = '\v';
                        i++;
                    /*
                    case 'h':
                        value = '\h';
                        i++;
                        */
                    default:
                        value = escaping;
                        i++;
                    }
                case '-':
                    if (is_in_char_class) {
                        is_char_range = true;
                        continue;
                    }
                    value = c;
                default:
                    value = c;
                    break;
                }

                is_alternation = is_alternation || regex_char_class[i+1] == '|';
                if (!first_pass && !(is_in_char_class || is_alternation)) {
                    break;
                }
                
                bool collision = marked[value] && ((first_pass && (classification_table.table[value] != target_class)) || (!first_pass)); //!first_pass
                //(classification_table.table[lower_value] == 0);
                bool any_collision = collision;
                //(target_class < classification_table[value]);
                //we only allow setting the character once
                classification_table.table[value] = !collision ? (char)target_class : (char)collision_class; //classification_table.table[value]
                marked[value] = (char)true;

                if (is_char_range) {
                    second_value = value;
                    uint lower_value = (first_value < second_value) ? first_value : second_value;
                    uint higher_value = (first_value < second_value) ? second_value : first_value;

                    printf("handling range: (%i-%i) (%i-%i)\n", first_value, second_value, lower_value, higher_value);
                    for (;lower_value < higher_value; lower_value++) {
                        bool collision_in_range = marked[value] && ((first_pass && classification_table.table[lower_value] != target_class) || (!first_pass)) ;//(collision_class != regex_char_class.len);
                        classification_table.table[lower_value] = collision_in_range ? (char)target_class : (char)collision_class;
                        marked[value] = (char)true;
                    }
                    is_char_range = false;
                } else {
                    first_value = value;
                }
                //if anything we wrote overwrote a previous value, move to the next "collision state"
                if (any_collision) {
                    classification_table.collisions[collision_class] = (char)target_class;
                    //classification_table.collisions[target_class] = (char)true;
                }

                collision_class += (char)any_collision;

                if (is_in_char_class || is_alternation) {
                    continue;
                } else { //read one character as a class
                    i++;
                    break;
                }
            }
            first_pass = false;

            printf("processed: %.*s next: %.*s\n", i, regex_char_class.ptr, regex_char_class.len-i, regex_char_class.ptr+i);
            printf("collision: %i\n", collision_class);
            printf("i: %i regex_char_class: %i\n", i, regex_char_class.len);
            //we've completed a step
            if (i < regex_char_class.len) {
                if (collision_class >= 255) {
                    printf("%s", "path 0!\n");
                    break;
                }
                //target_class = collision_class;
                collision_class = target_class + 1; //
                 printf("%s", "path 1!\n");
                continue;
            }
            printf("%s", "path 2!\n");
            break;
            //target_class++;

            //handles one step
        } while (true);
    }

    classification_table.output_classes = collision_class;

    return classification_table;
}
```

Here's what main looked like:
```c
fn int main(char [][] argv) {
    char[][] rules = {"[\\0- ]","0", "1", "[2-7]", "[8-9]", "[a-fA-F]", "_", "[g-zG-Z]", "\r", "\n", "[\\f\\v]", "[/]", "+", "-", "[xX]", "[bB]", "[rR]", "[eE]", "[pP]", "`", "\"", "[ \t]", "[!#$%&,:;<=>?@~^|\\\\]", "[({\\[]})]", "[)}\\]]", "\\0|\\2", "[\\xef-\\xff]"};

    //char[256] classes
    dfa::Classification_table dfa_class = dfa::create_distinct_classfication_table(rules);

    printf("%s","[\n");
    for (usize i = 0; i < dfa_class.table.len; i++) {
        printf("%i, //%i\n", (uint)dfa_class.table[i], i);
    }
    printf("]\n<input: %i, output: %i>\n", dfa_class.input_classes, dfa_class.output_classes);


    //try the above but concatenated into one

    char[][] rules2 = {"[\\0- ]""0" "1" "[2-7]" "[8-9]" "[a-fA-F]" "_" "[g-zG-Z]" "\r" "\n" "[\\f\\v]" "[/]" "+" "-" "[xX]" "[bB]" "[rR]" "[eE]" "[pP]" "`" "\"" "[ \t]" "[!#$%&:;<=>?@~^|\\\\]" "[({\\[]})]" "[)}\\]]" "\\0|\\2" "[\\xef-\\xff]"};
    dfa::Classification_table dfa_class2 = dfa::create_distinct_classfication_table(rules2);

    printf("%s","[\n");
    for (usize i = 0; i < dfa_class2.table.len; i++) {
        printf("%i, //%i\n", (uint)dfa_class2.table[i], i);
    }
    printf("]\n<input: %i, output: %i>\n", dfa_class2.input_classes, dfa_class2.output_classes);
}
```

And the offending printf that clearly indicate's something's up.
```
processing: [\0- ]01[2-7][8-9][a-fA-F]_[g-zG-Z]
[\f\v][/]+-[xX][bB][rR][eE][pP]`"[      ][!#$%&:;<=>?@~^|\\][({\[]})][)}\]]\0|\2[\xef-\xff]
handling range: (0-32) (0-32)
processed: [\0- ] next: 01[2-7][8-9][a-fA-F]_[g-zG-Z]
[\f\v][/]+-[xX][bB][rR][eE][pP]`"[      ][!#$%&:;<=>?@~^|\\][({\[]})][)}\]]\0|\2[\xef-\xff]
collision: 1
i: 6 regex_char_class: 124
path 1!
[
0, //0
0, //1
0, //2
````
Here we can see the algorithm took path 1... which is what I expect. i is sitting at 6 which is the second 0 in the string, which should be the start of the second loop. path 1 is in fact the right path to take...but then we should see a new line:
```
processing: 01[2-7][8-9][a-fA-F]_[g-zG-Z]
[\f\v][/]+-[xX][bB][rR][eE][pP]`"[      ][!#$%&:;<=>?@~^|\\][({\[]})][)}\]]\0|\2[\xef-\xff]
```
which is the top of the do loop.

**Comment by lerno** [comment] 2022-08-10 14:14
Do you have a smaller example to reproduce this?

**Comment by Andersama** [comment] 2022-08-10 14:16
Not yet...but*, in theory something's gone horribly wrong because the compilation is producing two different results between:
```c
while (true) {
//some things
}
```
and 
```c
do {
//some things
} while(true);

**Comment by lerno** [comment] 2022-08-10 14:17
Ok, I'll have a look and see why.

**Comment by Andersama** [comment] 2022-08-10 14:24
I'm pretty sure the output from 
```c
while (true) {
//some things
}
```
is correct, although I think I have a bug in my algorithm.

**Comment by lerno** [comment] 2022-08-10 14:31
I've come up with a fix. Deploying it as soon as possible.

**Comment by Andersama** [comment] 2022-08-10 14:35
From what I remember of the codegen I think you had do{} while() 's add an additional function body? That would make sense why it run's once...but it should still end up being an infinite loop if that were the case, which is odd.

**Comment by lerno** [comment] 2022-08-10 14:38
I pushed the fix to master. Basically it was a rewrite of do { } while to a for statement that was incorrect for the infinite loop case.

**Comment by lerno** [comment] 2022-08-10 14:40
Hopefully this was the only miscompilation.

**Comment by Andersama** [comment] 2022-08-10 14:41
Well...I'll definitely let you know if I find more.

**Comment by Andersama** [comment] 2022-08-10 14:48
Looking at your code fix, I'd be curious what the output was before the edit. Just intuitively a do {} while() is a while() {} with an extra loop. How'd it end up not in an infinite loop anyway?

**Closed** 2022-08-10 16:33 UTC

**Comment by lerno** [comment] 2022-08-10 16:54
There's special code because of the `do { };` construct. So what happened was that `do { } while(true);` was rewritten as `do {};` which is the same as `do { } while(false);`
